// components/ui/social/data.ts

export const clubsData = [
  {
    id: "1",
    name: "Les Jardiniers Urbains",
    desc: "Cultive des potagers partagés en ville 🌱",
    participants: 42,
    joined: false,
  },
  {
    id: "2",
    name: "Cyclistes Solidaires",
    desc: "Promouvoir la mobilité douce 🚲",
    participants: 18,
    joined: false,
  },
  {
    id: "3",
    name: "Zéro Déchet",
    desc: "Réduire les emballages à usage unique ♻️",
    participants: 25,
    joined: false,
  },
  {
    id: "4",
    name: "Marche Verte",
    desc: "Organisation de marches écologiques 🌍",
    participants: 60,
    joined: false,
  },
  {
    id: "5",
    name: "Les Abeilles Libres",
    desc: "Protection des pollinisateurs 🐝",
    participants: 34,
    joined: false,
  },
];

export const defisData = [
  {
    id: "1",
    name: "Défi Vélo",
    desc: "Utilise ton vélo au lieu de ta voiture pendant 7 jours 🚴‍♂️",
    places: 6,
    mode: "solo",
    joined: false,
  },
  {
    id: "2",
    name: "Semaine Sans Plastique",
    desc: "Évite le plastique à usage unique toute la semaine 🌊",
    places: 8,
    mode: "équipe",
    joined: false,
  },
  {
    id: "3",
    name: "Défi Compost",
    desc: "Transforme tes déchets organiques en compost 🍂",
    places: 5,
    mode: "solo",
    joined: false,
  },
  {
    id: "4",
    name: "Marche pour la Planète",
    desc: "Participe à une marche écologique 🏃‍♀️",
    places: 12,
    mode: "équipe",
    joined: false,
  },
  {
    id: "5",
    name: "Zéro Énergie",
    desc: "Réduis ta consommation d’électricité pendant 3 jours 💡",
    places: 10,
    mode: "solo",
    joined: false,
  },
];

export const amisData = [
  {
    id: "1",
    name: "Sophie",
    points: 620,
    online: true,
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
  },
  {
    id: "2",
    name: "Lucas",
    points: 580,
    online: false,
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    id: "3",
    name: "Emma",
    points: 560,
    online: true,
    avatar: "https://randomuser.me/api/portraits/women/45.jpg",
  },
  {
    id: "4",
    name: "Noah",
    points: 530,
    online: true,
    avatar: "https://randomuser.me/api/portraits/men/40.jpg",
  },
  {
    id: "5",
    name: "Clara",
    points: 480,
    online: false,
    avatar: "https://randomuser.me/api/portraits/women/24.jpg",
  },
  {
    id: "6",
    name: "Léo",
    points: 460,
    online: true,
    avatar: "https://randomuser.me/api/portraits/men/36.jpg",
  },
  {
    id: "7",
    name: "Mila",
    points: 440,
    online: false,
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
  },
  {
    id: "8",
    name: "Nathan",
    points: 410,
    online: true,
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
  },
  {
    id: "9",
    name: "Lina",
    points: 390,
    online: false,
    avatar: "https://randomuser.me/api/portraits/women/55.jpg",
  },
  {
    id: "10",
    name: "Ethan",
    points: 370,
    online: true,
    avatar: "https://randomuser.me/api/portraits/men/60.jpg",
  },
];
